# Global settings
title: Bitcoin Mumble Community
description: Connecting Bitcoin fans and traders
twitter_username: BitcoinMumble
github_username: bitcoin-mumble

timezone: Etc/UTC

# Site structure
paginate: 10
paginate_path: /blog/:num/

recent_posts: 5
excerpt_link: Read More
titlecase: true
category_dir: blog/categories

include: ['_pages']

# URLs
permalink: /:categories/:year/:title

# Author related
author_dir: blogs

##########
# Authors
authors:
  sirmeow:
    name: SirMeow
    site: http://twitter.com/OneSirMeow
    twitter: OneSirMeow
    github: cryptagoras
    telegram: SirMeow
    byline: Multitasking while multitasking while multitasking

  cryptobloomberg:
    name: Crypto.Bloomberg
    site: http://www.bitcoinmumble.com
